# Generated by Django 2.0.3 on 2019-07-12 02:07

from django.db import migrations

from django.contrib.auth.models import User


def add_user(apps, schema_editor):
    harshini_user = User.objects.create_user('harshini', 'harshini@gmail.com', 'pass')
    harshini_user.last_name = "Kuchibhotla"
    harshini_user.first_name = "Harshini"

    kavya_user = User.objects.create_user('kavya', 'kavya@gmail.com', 'pass')
    kavya_user.last_name = "Kuchibhotla"
    kavya_user.first_name = "Kavya"

    harshini_user.save()
    kavya_user.save()


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(add_user),
    ]
